spring:
  application:
    name: mcp-sparql-server
  ai:
    mcp:
      server:
        stdio: true
        name: jena-sparql
        version: 0.0.1
        type: SYNC
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true